#
# MySQL virtualizált példány a példaprogramokhoz.
# Docker és docker-compose telepítése után elindítható "docker-compose up -d" paranccsal.
#
# command-line csatlakozás:
#   mysql -h 127.0.0.1 -P 3306 -D webprog -u root -pwf24j2ucQYb5adMM7Nifk5ii
#   docker exec -it mysql mysql -D webprog -u root -pwf24j2ucQYb5adMM7Nifk5ii
#

version: '3.5'

services:

  db:
    image: mysql:5.7.24
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wf24j2ucQYb5adMM7Nifk5ii
      MYSQL_DATABASE: webprog
      MYSQL_USER: webprog
      MYSQL_PASSWORD: VgJUjBd8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - "webprogexamplesvolume:/var/lib/mysql"

volumes:
  webprogexamplesvolume:
